config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :admin
  resources :restaurants
  resources :menus
  resources :items
  root 'restaurants#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :menu
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_many :items	
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :items

	has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


  	# Search form
  	def self.search(search)
  		if search
  			Restaurant.where("name LIKE ? OR tags LIKE ?", "%#{search}%", "%#{search}%")
  		else
  			Restaurant.all
  		end
  	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	def index
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	restaurants_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :find_params, only: [:show, :edit, :update, :destroy]
  def new
    if !user_signed_in?
      redirect_to(:back)
    end
  	@items = Item.where(menuId:params[:menu_id]).where("created_at >= ?", Time.zone.now.beginning_of_day)
  	@item = Item.new

    if !params[:restaurant_id] || !params[:menu_id]
      redirect_to admin_index_path
    end

  end
  def create
  	@item = Item.create(item_params)
  	if @item.save
  		redirect_to(:back)
  	end
  end

  def edit
    if !user_signed_in?
      redirect_to(:back)
    end
  end

  def update
  	@item = Item.find(find_params)
  	if @item.update(item_params)
      redirect_to :back,  :notice => "Data has been updated." 
  	end
  end

  def destroy
    if user_signed_in?
    	@item = Item.find(find_params)
    	if @item.destroy
          if(params.has_key?(:fromMenu))
      		  redirect_to(:back)
          else
            redirect_to controller: 'items', action: 'new', restaurant_id: @item.restaurantId, menu_id: @item.menuId
        
        end
    	end
    end
  end

  private

  def find_params
  	@item = Item.find(params[:id])
  end

  def item_params
  	params.require(:item).permit(:name, :price, :description, :restaurantId, :menuId)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController	
	before_action :find_params, only: [:show, :edit, :update, :destroy]
  def new
    if !user_signed_in?
      redirect_to(:back)
    end
  	@menus = Menu.where(restaurantId: params[:restaurant_id]).where("created_at >= ?", Time.zone.now.beginning_of_day)
  	@menu = Menu.new

    if !params[:restaurant_id]
      redirect_to admin_index_path
    end
    @id = params[:id]
    @id = @restaurant_id
  end
  def create
  	@menu = Menu.create(menu_params)
  	if @menu.save
  		# redirect_to new_menu_path
      redirect_to(:back)
  	end
  end

  def edit
    if !user_signed_in?
      redirect_to(:back)
    end
  end

  def update
  	@menu = Menu.find(find_params)
  	if @menu.update(menu_params)
  		redirect_to controller: 'menus', action: 'new', restaurant_id: @menu.restaurantId
  	end
  end

  def destroy
    if user_signed_in?
    	@menu = Menu.find(find_params)
    	if @menu.destroy
        redirect_to controller: 'menus', action: 'new', restaurant_id: @menu.restaurantId
    	end
    end
  end

  private

  def find_params
  	@menu = Menu.find(params[:id])
  end

  def menu_params
  	params.require(:menu).permit(:name, :orderInList, :restaurantId)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :find_params, only: [:show, :edit, :update, :destroy]
	def index
		@restaurants = Restaurant.search(params[:search])
	end
	def show
		@restaurant = Restaurant.find(find_params)
		@menu = Menu.new
		@item = Item.new

		@menus = Menu.where(restaurantId: params[:id]).order("orderInList ASC")
		@items = Item.all
	end

	def new
		@restaurant = Restaurant.new
		if !user_signed_in?
			redirect_to(:back)
		end
	end

	def create
		@restaurant = Restaurant.create(restaurant_params)
		if @restaurant.save
			redirect_to restaurants_path, flash: { notice: "Data has been inserted" }
		end
	end

	def edit
		if !user_signed_in?
			redirect_to(:back)
		end
	end

	def update
		if @restaurant.update(restaurant_params)
			redirect_to restaurants_path, flash: { notice: "Data has been updated" }
		end
	end

	def destroy
		if user_signed_in?
			@restaurant = Restaurant.find(find_params)
			if @restaurant.destroy
				redirect_to restaurants_path
			end
		end
	end

	private
	def find_params
		@restaurant = Restaurant.find(params[:id])
	end

	def restaurant_params
		params.require(:restaurant).permit(:name, :phone, :location, :city, :country, :minPrice, :isDelivery, :code, :avatar, :tags)
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # autocomplete OFF
  def text_field(*args)
     unless args.last.kind_of?(Hash) then
      args << {}
     end
 
     args.last[:autocomplete] = 'off' \
         unless args.last[:autocomplete]
     super(*args)
   end
   # autocomplete OFF -- END
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/items/_form.html.erb
<div class="formHolder">
	<div class="title">
		<% if @item.new_record? %>
			New Item
		<% else %>
			Edit Item
		<% end %>
		<span>
			<% if @item.new_record? %>
				<%= link_to image_tag("cancel.png", :border => 0), {:action => 'show', :controller => 'restaurants', :id => params[:restaurant_id]} %>
			<% elsif !params[:fromMenu] %>
				<%= link_to image_tag("cancel.png", :border => 0), {:action => 'new', :controller => 'items', :restaurant_id => params[:restaurant_id], :menu_id => params[:menu_id]} %>
			<% else %>
				<%= link_to image_tag("cancel.png", :border => 0), {:action => 'show', :controller => 'restaurants', :id => params[:restaurant_id]} %>
			<% end %>
		</span>
	</div>
	<%= simple_form_for @item do |t| %>
	<%= t.input :name, required: true,  :placeholder => "Item name", :label => false %>
	<%= t.input :price, required: true, :placeholder => "Price", :label => false %>
	<%= t.input :description, :placeholder => "Descripe your Item ...", :label => false %>
	<%= t.input :restaurantId, :as => :hidden, input_html: {:value => params[:restaurant_id]} %>
	<%= t.input :menuId, :as => :hidden, input_html: {:value => params[:menu_id]} %>

	<%= t.submit  :class => "btn" %>
		<div class="distroyBtn">
			<% if !@item.new_record? %>
				<%= link_to 'Delete this Restaurant', { action: :destroy, id: @item.id }, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</div>
		<div class="clear"></div>
	<% end %>

</div>

<% if @item.new_record? %>
	<% @items.each do |item| %>
		<div class="menu">
			<%= item.name %> | <%= number_to_currency(item.price) %>
			<span id="edit">
				<%= link_to "Edit", edit_item_path(:id => item, :restaurant_id => params[:restaurant_id], :menu_id => params[:menu_id]) %>
			</span>
		</div>
	<% end %>
<% end %>

<% if flash[:notice] %>
	<div class="notify" id="notify">
		<%= flash[:notice] %>
	</div>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <title>Restaurant POS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

	<script>
		// toggle category
		$(".category").click(function () {

	    $header = $(this);
	    $content = $header.next();
	    $content.slideToggle(200, function () {	        
	    });

	});
	</script>
</body>
</html>

app/views/menus/_form.html.erb
<div class="formHolder">
	<div class="title">
		<% if @menu.new_record? %>
			New Menu
		<% else %>
			Edit Menu
		<% end %>
		<span>
			<% if @menu.new_record? %>
				<%= link_to image_tag("cancel.png", :border => 0), {:action => 'show', :controller => 'restaurants', :id => params[:restaurant_id]} %>
			<% elsif params[:restaurant_id] and !params[:mainForm] %>
				<%= link_to image_tag("cancel.png", :border => 0), {:action => 'show', :controller => 'restaurants', :id => params[:restaurant_id]} %>
			<% elsif params[:mainForm] %>
				<%= link_to image_tag("cancel.png", :border => 0), {:action => 'new', :controller => 'menus', :restaurant_id => params[:restaurant_id]} %>
			<% else %>
				<%= link_to image_tag("cancel.png", :border => 0), {:action => 'new', :controller => 'menus', :restaurant_id => params[:restaurant_id]} %>
			<% end %>
		</span>
	</div>
	<%= simple_form_for @menu do |t| %>
	<%= t.input :name, required: true,  :placeholder => "Menu/Category name", :label => false %>
	<% if @menu.new_record? %>
		<%= t.input :orderInList, :as => :hidden, input_html: {value: '1'},  :label => false %>
	<% else %>
		<%= t.input :orderInList, :input_html => { :class => "orderInList" },  :label => false %>
	<% end %>
		<%= t.input :restaurantId, :as => :hidden, input_html: {:value => params[:restaurant_id]} %>
	<%= t.submit  :class => "btn" %>
		<div class="distroyBtnMenu">
			<% if !@menu.new_record? %>
				<%= link_to 'Delete this Menu', { action: :destroy, id: @menu.id }, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</div>
		<div class="clear"></div>
	<% end %>
</div>
<% if @menu.new_record? %>
	<% @menus.each do |menu| %>
		<div class="menu">
			<%= menu.name %>
			<span id="edit">
				<%= link_to "Edit", edit_menu_path(:id => menu, :restaurant_id => params[:restaurant_id], :mainForm => "Yes") %>
			</span>
		</div>
	<% end %>
<% end %>

app/views/menus/edit.html.erb
<%= render 'form' %>

app/views/menus/new.html.erb
<%= render 'form' %>

app/views/restaurants/_form.html.erb
<div class="formHolder">
	<div class="title">
		<% if @restaurant.new_record? %>
			New Restaurant
		<% else %>
			Edit Restaurant
		<% end %>
		<span>
			<%= link_to image_tag("cancel.png", :border => 0), {:action => 'index', :controller => 'restaurants'} %>
		</span>
	</div>
	<%= simple_form_for @restaurant do |t| %>
	<%= t.input :name, required: true,  :placeholder => "Restaurant name", :label => false %>
	<%= t.input :phone, required: true, :placeholder => "Phone", :label => false %>
	<%= t.input :location, required: true, :placeholder => "Location", :label => false %>
	<%= t.input :city, required: true,  :placeholder => "City", :label => false %>
	<%= t.input :country,   priority: [ "US" ], :label => false %>
	<%= t.input :postalCode,:as => :hidden,  :placeholder => "Postal code", disabled: true, :label => false %>
	<%= t.input :minPrice,  :placeholder => "Minimum Price", :label => false %>
	<%= t.input :tags,  :placeholder => "Example: BBQ, Italian, Indian...", :label => false %>

	<%= t.input :avatar, :label => false %>
	
	<%= t.input :code, :as => :hidden, :label => false %>
	<div class="newLineLabel">
		<%= t.input :isDelivery, :label => "Delivery", :class => "isDelivery" %>
	</div>
	<%= t.submit  :class => "btn" %>
		<div class="distroyBtn">
			<% if !@restaurant.new_record? %>
				<%= link_to 'Delete this Restaurant', { action: :destroy, id: @restaurant.id }, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</div>
		<div class="clear"></div>
	<% end %>

</div>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

app/views/restaurants/index.html.erb
<header>
	<%= link_to 'New Restaurants', new_restaurant_path %> | 
	<% if user_signed_in? %>
		<%= link_to 'Logout', destroy_user_session_path, :method => :delete %> 
	<% else %>
		<%= link_to 'Login', new_user_session_path %>
	<% end %>
</header>


<div class="search">
	<%= form_tag restaurants_path, :method => "get" do %>
		<%= text_field_tag :search, params[:search], :placeholder => "E.g. Sushi, pad thai, Bob's pizza", :autocomplete => :off %>
		<%= submit_tag "Search", :name => nil %>
		<%= link_to "Reset Search", restaurants_path, :class => "reset" %>
	<% end %>
</div>
<div class="clear"></div>

<div class="restaurantsHolder">
	<% @restaurants.each do |restaurant| %>
			<div class="restaurant">
				<%= link_to restaurant do %>
					<%= image_tag restaurant.avatar.url(:thumb), :class => "restaurantAvatar" %>
				<% end %>

				<h3><%= link_to restaurant.name, restaurant %></h3>
				<p class="tags"><%= restaurant.tags %></p>
				<% if user_signed_in? %>
				<p><%= link_to "Edit", edit_restaurant_path(restaurant) %></p>
				<% end %>
			</div>
	<% end %>
	<% if @restaurants.count < 1 %>
		<p>No results match your search</p>
	<% end %>
</div>



<% if flash[:notice] %>
	<div class="notify" id="notify">
		<%= flash[:notice] %>
	</div>
<% end %>	

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="infoHolder">
	<div class="restaurantHeader">
		<%= image_tag @restaurant.avatar.url(:thumb), :class => "restaurantAvatar" %>
		<h1><%= @restaurant.name %></h1>
		<p id="tags"><%= @restaurant.tags %></p>
		<p id="location"><%= @restaurant.location %>, <%= @restaurant.city %></p>
		<p id="phone"><%= number_to_phone(@restaurant.phone, area_code: true) %></p>
	</div>
	<% if user_signed_in? %>
		<%= link_to "Add new menu", new_menu_path(:restaurant_id => @restaurant.id), class: "button add mb40", id: "add_new_menu" %>
	<% end %>
</div>
<div class="clear" />
<div class="menuHolder">
		<% @menus.each do |menu| %>
			<% 
			# @count = Item.where(:menuId => menu.id).count
			# if @count > 0
			%>
				<div class="category">
						<%= menu.name %> 
						<% if user_signed_in? %>
							<div class="floatRight"><%= link_to "Add Item", new_item_path(:restaurant_id => @restaurant.id, :menu_id => menu.id), class: "button add" %><%= link_to "Edit menu", edit_menu_path(:id => menu, :restaurant_id => params[:id]), class: "button edit" %></div>
						<% end %>
				</div>
				<div>
				<table class="table table-striped">
					<% 
					@items = Item.where(menuId: menu.id)
					@items.each do |item| 
					%>
						
							<td class="item noBottomBorder">
							<h1><%= item.name %></h1>
							<span><%= number_to_currency(item.price) %></span>
							<% if item.description? %>
							<p class="description" title="<%= item.description %>"><%= truncate item.description, length: 150 %></p>
							<div>
								<% if user_signed_in? %>
									<%= link_to 'Edit Item', edit_item_path(item.id, :menu_id => menu.id, :restaurant_id => params[:id], :fromMenu => "1"), class: "button edit" %>
									<%= link_to 'Delete this Item', { action: :destroy, :controller => 'items', id: item.id, :fromMenu => "1" }, method: :delete, data: { confirm: 'Are you sure?' }, class: "remove" %>
								<% end %>
							</div>
							<% else %>
								<p id="noDesc">No Description Founded</p>
								<% if user_signed_in? %>
									<%= link_to 'Edit Item', edit_item_path(item.id, :menu_id => menu.id, :restaurant_id => params[:id], :fromMenu => "1"), class: "button edit" %>
									<%= link_to 'Delete this Item', { action: :destroy, :controller => 'items', id: item.id, :fromMenu => "1" }, method: :delete, data: { confirm: 'Are you sure?' }, class: "remove" %>
								<% end %>
							<% end %>
							</td>
						
					<% end %>
					</table>
				</div>
				<div class="clear" />
			<% # end %>
		<% end %>
</div>